### ISSUE TITLE
https://hrshadhin.wordpress.com/tag/hddtemp/ needs updated link

### ISSUE THREAD

**Issue by dannn-o** [hrshadhin/conky-theme-seamod-mix#1]
Still in the process of trying to install the Conky theme (looks great!).  I initially found your Blog post with a Dropbox link at [https://hrshadhin.wordpress.com/tag/hddtemp/](url), but the Dropbox link is no longer valid (404 error).  I'm opening this to let you know, in case you'd like to modify the Blog post to point here instead of [https://dl.dropboxusercontent.com/u/67410532/software/Conky_Seamod_Mix.zip](url)

**Comment by hrshadhin** [comment]
Thanks for reporting. Issue has been solved.
